// Generated by the Supabase MCP tool generate_typescript_types after migration 0007.
// Do not edit by hand: the backend lead regenerates it after every migration.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; display_name: string | null; locale: string; premium_until: string | null; created_at: string };
        Insert: { id: string; display_name?: string | null; locale?: string; premium_until?: string | null };
        Update: { display_name?: string | null; locale?: string };
        Relationships: [];
      };
      plants: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          species: string | null;
          pot_size_cm: number | null;
          light: 'low' | 'medium' | 'bright';
          summer_interval_days: number;
          photo_path: string | null;
          created_at: string;
        };
        Insert: {
          owner_id: string;
          name: string;
          species?: string | null;
          pot_size_cm?: number | null;
          light?: 'low' | 'medium' | 'bright';
          summer_interval_days?: number;
          photo_path?: string | null;
        };
        Update: Partial<Database['public']['Tables']['plants']['Insert']>;
        Relationships: [];
      };
      care_events: {
        Row: { id: string; plant_id: string; kind: 'water' | 'fertilize' | 'repot'; source: 'app' | 'widget' | 'notification'; done_at: string };
        Insert: { plant_id: string; kind: 'water' | 'fertilize' | 'repot'; source: 'app' | 'widget' | 'notification'; done_at?: string };
        Update: never;
        Relationships: [];
      };
    };
    Functions: {
      next_due_at: { Args: { p_plant_id: string }; Returns: string };
    };
  };
};

// Shared contract with the native lanes (widget storage and deep links).
export const APP_GROUP = 'group.com.example.leafwise';
export const WIDGET_STORE_KEY = 'leafwise.widget.dueToday';
export const DEEP_LINK = { plant: (id: string) => `leafwise://plant/${id}` } as const;
